{
 "title": "hw dashboard",
 "description": "Prometheus. Grafana",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "histogram_quantile-95-service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, uri) (rate(http_server_requests_seconds_bucket{uri=~\"/.*\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "histogram_quantile-99-service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, uri) (rate(http_server_requests_seconds_bucket{uri=~\"/.*\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "histogram_quantile--05-service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, uri) (rate(http_server_requests_seconds_bucket{uri=~\"/.*\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri=~\"/user/.*\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BASE",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (uri)(rate(http_server_requests_seconds_bucket{uri=~\"/.*\", status=~\"200\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}