apiVersion: v1
kind: Service
metadata:
  name: hw-service
  annotations:
    prometheus.io/port  : "metrics"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/part-of: hw-metrics

spec:
  selector:
    env: hw
  ports:
    - protocol  : TCP
      port      : 80
      targetPort: 8000
      name: "metrics"
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-svc

spec:
  selector:
    env: postgres-app
  ports:
    - port      : 5432
      targetPort: 5432